import { describe, expect, test } from 'bun:test';
import { generateSkillMd } from './skill.js';
import type { Manifest } from '../types/manifest.js';

describe('generateSkillMd', () => {
  const baseManifest: Manifest = {
    version: 'v0',
    name: 'Test Service',
    description: 'A test service',
    register: '/api/auth/register',
    actions: [
      {
        id: 'list-items',
        method: 'GET',
        path: '/api/items',
        description: 'List all items',
      },
      {
        id: 'create-item',
        method: 'POST',
        path: '/api/items',
        description: 'Create a new item',
      },
    ],
  };

  test('generates valid YAML frontmatter', () => {
    const result = generateSkillMd(baseManifest, 'https://example.com', 'manifest.json');

    expect(result).toContain('---');
    expect(result).toContain('name: test-service');
    expect(result).toContain('description: A test service');
    expect(result).toContain('homepage: https://example.com');
    expect(result).toContain('manifest: manifest.json');
  });

  test('includes service name as title', () => {
    const result = generateSkillMd(baseManifest, 'https://example.com', 'manifest.json');

    expect(result).toContain('# Test Service');
  });

  test('includes description when provided', () => {
    const result = generateSkillMd(baseManifest, 'https://example.com', 'manifest.json');

    expect(result).toContain('A test service');
  });

  test('handles manifest without description', () => {
    const manifestNoDesc: Manifest = {
      ...baseManifest,
      description: undefined,
    };

    const result = generateSkillMd(manifestNoDesc, 'https://example.com', 'manifest.json');

    // Should use name as fallback in frontmatter
    expect(result).toContain('description: Test Service');
  });

  test('includes installation instructions with correct URL', () => {
    const result = generateSkillMd(baseManifest, 'https://api.myservice.com', 'manifest.json');

    expect(result).toContain('## Installation');
    expect(result).toContain('bun install -g @ai26/zag');
    expect(result).toContain('zag setup https://api.myservice.com');
  });

  test('includes usage instructions with correct URL', () => {
    const result = generateSkillMd(baseManifest, 'https://api.myservice.com', 'manifest.json');

    expect(result).toContain('## Usage');
    expect(result).toContain('zag exec https://api.myservice.com <action-id>');
  });

  test('references manifest file in API Reference section', () => {
    const result = generateSkillMd(baseManifest, 'https://example.com', 'manifest.json');

    expect(result).toContain('## API Reference');
    expect(result).toContain('See the [manifest](manifest.json)');
  });

  test('lists all actions with descriptions', () => {
    const result = generateSkillMd(baseManifest, 'https://example.com', 'manifest.json');

    expect(result).toContain('### Available Actions');
    expect(result).toContain('- `list-items`: GET /api/items - List all items');
    expect(result).toContain('- `create-item`: POST /api/items - Create a new item');
  });

  test('handles actions without descriptions', () => {
    const manifestNoActionDesc: Manifest = {
      ...baseManifest,
      actions: [
        {
          id: 'ping',
          method: 'GET',
          path: '/ping',
        },
      ],
    };

    const result = generateSkillMd(manifestNoActionDesc, 'https://example.com', 'manifest.json');

    expect(result).toContain('- `ping`: GET /ping');
    expect(result).not.toContain('- `ping`: GET /ping -');
  });

  test('converts service name with spaces to kebab-case', () => {
    const manifestWithSpaces: Manifest = {
      ...baseManifest,
      name: 'My Awesome Service',
    };

    const result = generateSkillMd(manifestWithSpaces, 'https://example.com', 'manifest.json');

    expect(result).toContain('name: my-awesome-service');
  });

  test('includes footer with ZAG link', () => {
    const result = generateSkillMd(baseManifest, 'https://example.com', 'manifest.json');

    expect(result).toContain('*Generated by [ZAG](https://github.com/ai26/zag)*');
  });

  test('handles empty actions array', () => {
    const manifestNoActions: Manifest = {
      ...baseManifest,
      actions: [],
    };

    const result = generateSkillMd(manifestNoActions, 'https://example.com', 'manifest.json');

    expect(result).toContain('### Available Actions');
    // Should not throw, just have empty list
    expect(result).toBeDefined();
  });

  test('handles different HTTP methods', () => {
    const manifestAllMethods: Manifest = {
      ...baseManifest,
      actions: [
        { id: 'get-item', method: 'GET', path: '/api/items/:id' },
        { id: 'create-item', method: 'POST', path: '/api/items' },
        { id: 'update-item', method: 'PUT', path: '/api/items/:id' },
        { id: 'patch-item', method: 'PATCH', path: '/api/items/:id' },
        { id: 'delete-item', method: 'DELETE', path: '/api/items/:id' },
      ],
    };

    const result = generateSkillMd(manifestAllMethods, 'https://example.com', 'manifest.json');

    expect(result).toContain('GET /api/items/:id');
    expect(result).toContain('POST /api/items');
    expect(result).toContain('PUT /api/items/:id');
    expect(result).toContain('PATCH /api/items/:id');
    expect(result).toContain('DELETE /api/items/:id');
  });
});
