import type { Manifest, ManifestAction } from '../types/manifest.js';

export function generateSkillMd(manifest: Manifest, serviceUrl: string, manifestPath: string): string {
  const lines: string[] = [];

  // YAML frontmatter - minimal, references manifest
  lines.push('---');
  lines.push(`name: ${manifest.name.toLowerCase().replace(/\s+/g, '-')}`);
  lines.push(`description: ${manifest.description || manifest.name}`);
  lines.push(`homepage: ${serviceUrl}`);
  lines.push(`manifest: ${manifestPath}`);
  lines.push('---');
  lines.push('');

  // Title and description
  lines.push(`# ${manifest.name}`);
  lines.push('');
  if (manifest.description) {
    lines.push(manifest.description);
    lines.push('');
  }

  // Installation
  lines.push('## Installation');
  lines.push('');
  lines.push('```bash');
  lines.push('# Install zag CLI');
  lines.push('bun install -g @ai26/zag');
  lines.push('');
  lines.push('# Register with the service');
  lines.push(`zag setup ${serviceUrl}`);
  lines.push('```');
  lines.push('');

  // Usage
  lines.push('## Usage');
  lines.push('');
  lines.push('After registration, execute actions:');
  lines.push('');
  lines.push('```bash');
  lines.push(`zag exec ${serviceUrl} <action-id> [--data '{"key": "value"}']`);
  lines.push('```');
  lines.push('');

  // Reference to manifest for API details
  lines.push('## API Reference');
  lines.push('');
  lines.push(`See the [manifest](${manifestPath}) for available actions and schemas.`);
  lines.push('');

  // List action IDs for quick reference
  lines.push('### Available Actions');
  lines.push('');
  for (const action of manifest.actions) {
    const desc = action.description ? ` - ${action.description}` : '';
    lines.push(`- \`${action.id}\`: ${action.method} ${action.path}${desc}`);
  }
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('*Generated by [ZAG](https://github.com/ai26/zag)*');

  return lines.join('\n');
}
